// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Head: typeof import('./src/components/Head.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Year: typeof import('./src/components/Year.vue')['default']
  }
}

export {}
