name: blog-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Commit files
        run: |
            cd .vitepress/dist 
            git init
            git config user.name "xieyezi"
            git config user.email "1435398529@qq.com"
            git add -A
            git commit -m 'deploy'

      - name: Push to github pages repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BLOG_ACCESS_TOKEN }}
          repository: "xieyezi/xieyezi.github.io"
          branch: master
          directory: ".vitepress/dist"
          force: true

